import { useEffect, useMemo, useRef, useState } from 'preact/hooks';
import { useStore } from '../app/context';
import { applyCompletion, composerCompletions } from '../domain/completions';
import { VoiceRecorder } from '../platform/voice';

export function Composer() {
  const store = useStore(); const file = useRef<HTMLInputElement>(null); const textarea = useRef<HTMLTextAreaElement>(null); const [menu, setMenu] = useState(false); const [voiceStatus, setVoiceStatus] = useState(''); const [recording, setRecording] = useState(false); const [completionIndex, setCompletionIndex] = useState(0);
  const voice = useMemo(() => new VoiceRecorder(), []); useEffect(() => () => voice.cancel(), [voice]);
  const completions = composerCompletions(store.prompt.value, store.config.agentNames); const project = store.projects.value.find((entry) => entry.id === store.activeProjectId.value); const bindingBlocked = store.draftActive.value && Boolean(project && project.available === false);
  const choose = (value: string) => { store.prompt.value = applyCompletion(store.prompt.value, value); setCompletionIndex(0); textarea.current?.focus(); };
  const sendOrCommand = () => {
    const value = store.prompt.value.trim(); const command = value.toLowerCase();
    if (/^\/side(?:\s|$)/i.test(value)) { const question = value.replace(/^\/side\b/i, '').trim(); store.sideQuestion.value = { ...store.sideQuestion.value, visible: true }; store.prompt.value = ''; if (question) void store.askSideQuestion(question); else void store.recoverSideQuestion(); return; }
    if (command === '/new') return store.newChat(); if (command === '/goal') { store.modal.value = 'goal'; return; } if (command === '/mcp') { store.modal.value = 'mcp'; void store.loadMCP(); return; } if (command === '/skills') { store.modal.value = 'skills'; void store.loadSkills(); return; }
    if (command === '/paths' || command === '/tree') { void store.loadBranchTree(); return; } if (command === '/worktree') { store.modal.value = 'worktrees'; void store.loadWorktrees(); return; }
    if (command === '/model' || command === '/effort') { store.modal.value = 'settings'; return; }
    if (command === '/undo' || command === '/redo') { store.prompt.value = ''; void store.mutateTranscript(command.slice(1) as 'undo' | 'redo'); return; }
    if (command === '/compact') { const session = store.activeSession.value; store.prompt.value = ''; if (session) void store.endpoints.compact(session.id).then(() => store.loadSession(session.id)); else store.toast('Start the conversation before compacting.', 'error'); return; }
    void store.send();
  };
  const toggleVoice = async () => { try { if (!recording) { await voice.start(); setRecording(true); setVoiceStatus('Recording… tap again to transcribe'); } else { setRecording(false); setVoiceStatus('Transcribing…'); const text = await voice.stop(store.endpoints); store.prompt.value = `${store.prompt.value}${store.prompt.value ? ' ' : ''}${text}`; setVoiceStatus(''); } } catch (error) { setRecording(false); setVoiceStatus(error instanceof Error ? error.message : String(error)); } };
  const pending = store.interjections.value.filter((entry) => entry.sessionId === store.activeSession.value?.id);
  return <footer class="composer" onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); if (event.dataTransfer?.files.length) store.addAttachments(event.dataTransfer.files); }}>
    <div class="composer-inner">
      {pending.length > 0 && <div class="pending-interjection-banner" role="list" aria-label="Pending messages">{pending.map((entry) => <div class={`pending-interjection-row ${entry.state}`} role="listitem" key={entry.id}><span class="pending-interjection-icon">⏳</span><span class="pending-interjection-text">{entry.content}</span><span class="pending-interjection-label">({entry.state === 'sending' ? 'deciding…' : entry.state})</span>{entry.state !== 'committed' && <button class="pending-interjection-cancel" onClick={() => void store.cancelInterjection(entry.id)}>Cancel</button>}</div>)}</div>}
      {voiceStatus && <div id="voiceStatus" class="voice-status" aria-live="polite">{voiceStatus}</div>}
      {store.attachments.value.length > 0 && <div id="attachmentsStrip" class="attachments">{store.attachments.value.map((attachment) => <div class="attachment-chip" key={attachment.id}>{attachment.previewURL && attachment.type.startsWith('image/') && <img src={attachment.previewURL} alt="" />}<span>{attachment.name}</span><button type="button" aria-label={`Remove ${attachment.name}`} onClick={() => store.removeAttachment(attachment.id)}>×</button></div>)}</div>}
      {store.goal.value && <button type="button" id="goalChip" class={`goal-chip goal-${store.goal.value.status || 'active'}`} onClick={() => { store.modal.value = 'goal'; }}>🎯 {store.goal.value.status || 'active'}{store.goal.value.token_budget ? ` · ${store.goal.value.tokens_used || 0}/${store.goal.value.token_budget} tok` : ''} · {store.goal.value.objective}</button>}
      {bindingBlocked && <div class="composer-binding-error" role="alert">This project is unavailable. Restore it or choose No project before sending.</div>}
      <div class="composer-box">
        <button class="composer-icon-btn attach-btn" id="attachBtn" type="button" aria-label="Add" aria-expanded={menu} onClick={() => setMenu(!menu)}>＋</button>
        {menu && <div class="composer-add-menu" id="addMenu" role="menu"><button type="button" role="menuitem" onClick={() => { file.current?.click(); setMenu(false); }}>📎 Upload file</button>{store.config.locationSharing && <button type="button" role="menuitem" onClick={() => { void store.shareLocation(); setMenu(false); }}>⌖ Share current location</button>}<button type="button" role="menuitem" onClick={() => { store.modal.value = 'mcp'; void store.loadMCP(); setMenu(false); }}>▦ MCP servers</button><button type="button" role="menuitem" onClick={() => { store.modal.value = 'goal'; setMenu(false); }}>🎯 Set goal…</button>{store.worktreesEnabled.value && <button type="button" role="menuitem" onClick={() => { store.modal.value = 'worktrees'; void store.loadWorktrees(); setMenu(false); }}>⌥ Worktrees</button>}</div>}
        <input ref={file} type="file" id="fileInput" multiple hidden onChange={(event) => { if (event.currentTarget.files) store.addAttachments(event.currentTarget.files); event.currentTarget.value = ''; }} />
        {completions.length > 0 && <div class="slash-command-menu" id="slashCommandMenu" role="listbox" aria-label="Composer completions">{completions.map((entry, index) => <button type="button" role="option" aria-selected={completionIndex === index} class={completionIndex === index ? 'active' : ''} key={entry.value} onMouseDown={(event) => { event.preventDefault(); choose(entry.value); }}><strong>{entry.label}</strong><span>{entry.description}</span></button>)}</div>}
        <textarea ref={textarea} id="promptInput" class="prompt" rows={1} placeholder={store.streaming.value ? 'Type to interject…' : 'Message…'} aria-label="Message" autoComplete="off" spellcheck={false} aria-autocomplete="list" aria-controls="slashCommandMenu" aria-activedescendant={completions[completionIndex]?.value} aria-expanded={completions.length > 0} value={store.prompt.value} onPaste={(event) => { const files = Array.from(event.clipboardData?.items || []).filter((item) => item.kind === 'file').map((item) => item.getAsFile()).filter((item): item is File => Boolean(item)); if (files.length) store.addAttachments(files); }} onInput={(event) => { store.prompt.value = event.currentTarget.value; event.currentTarget.style.height = 'auto'; event.currentTarget.style.height = `${Math.min(event.currentTarget.scrollHeight, 200)}px`; setCompletionIndex(0); }} onKeyDown={(event) => {
          if (completions.length && ['ArrowDown', 'ArrowUp'].includes(event.key)) { event.preventDefault(); setCompletionIndex((index) => (index + (event.key === 'ArrowDown' ? 1 : -1) + completions.length) % completions.length); return; }
          if (completions.length && (event.key === 'Tab' || (event.key === 'Enter' && !event.shiftKey))) { event.preventDefault(); choose(completions[completionIndex].value); return; }
          if (event.key === 'Escape' && completions.length) { event.preventDefault(); store.prompt.value += ' '; return; }
          if (event.key === 'Enter' && !event.shiftKey && !event.isComposing) { event.preventDefault(); if (store.streaming.value) void store.interject(store.prompt.value).then(() => { store.prompt.value = ''; }); else sendOrCommand(); }
        }} />
        <div class="composer-actions">{store.streaming.value && <button class="stop-btn visible" id="stopBtn" type="button" onClick={() => void store.cancel()}>Stop</button>}{'MediaRecorder' in window && <button class={`composer-icon-btn voice-btn ${recording ? 'recording' : ''}`} id="voiceBtn" type="button" aria-label={recording ? 'Stop recording' : 'Record voice message'} onClick={() => void toggleVoice()}>●</button>}<button class={`send-btn ${store.streaming.value ? 'interject' : ''}`} id="sendBtn" type="button" title={bindingBlocked ? 'Project unavailable' : ''} aria-label={store.streaming.value ? 'Interject' : 'Send message'} disabled={bindingBlocked || (!store.prompt.value.trim() && !store.attachments.value.length)} onClick={() => { if (store.streaming.value) void store.interject(store.prompt.value).then(() => { store.prompt.value = ''; }); else sendOrCommand(); }}><span class="arrow">↑</span></button></div>
      </div>
    </div>
  </footer>;
}
