import { useEffect, useId, useRef, useState } from 'preact/hooks';
import { useStore } from '../app/context';
import type { Goal } from '../domain/types';

function Overlay({ title, children, wide = false, close = true, onEscape }: { title: string; children: preact.ComponentChildren; wide?: boolean; close?: boolean; onEscape?: () => void }) {
  const store = useStore(); const dialog = useRef<HTMLDivElement>(null); const label = useId();
  useEffect(() => {
    const previous = document.activeElement as HTMLElement | null; const shell = document.getElementById('appShell'); if (shell) shell.inert = true;
    requestAnimationFrame(() => dialog.current?.querySelector<HTMLElement>('[autofocus],button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled])')?.focus());
    return () => { if (shell) shell.inert = false; previous?.focus({ preventScroll: true }); };
  }, []);
  return <div class="modal-overlay" role="presentation" onMouseDown={(event) => { if (close && event.target === event.currentTarget) store.modal.value = ''; }}><div ref={dialog} class={`modal ${wide ? 'wide-modal' : ''}`} role="dialog" aria-modal="true" aria-labelledby={label} tabIndex={-1} onKeyDown={(event) => {
    if (event.key === 'Escape' && (close || onEscape)) { event.preventDefault(); if (onEscape) onEscape(); else store.modal.value = ''; return; } if (event.key !== 'Tab') return;
    const items = [...event.currentTarget.querySelectorAll<HTMLElement>('button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),a[href],[tabindex]:not([tabindex="-1"])')]; if (!items.length) { event.preventDefault(); event.currentTarget.focus(); return; }
    const first = items[0]; const last = items.at(-1)!; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); }
  }}><div class="modal-title-row"><h2 id={label}>{title}</h2>{close && <button class="icon-btn" type="button" aria-label={`Close ${title}`} onClick={() => { store.modal.value = ''; }}>✕</button>}</div>{children}</div></div>;
}

function Settings() {
  const store = useStore(); const [token, setToken] = useState(store.token.value); const [provider, setProvider] = useState(store.selectedProvider.value); const [model, setModel] = useState(store.selectedModel.value); const [effort, setEffort] = useState(store.selectedEffort.value); const [reasoning, setReasoning] = useState(store.selectedReasoningMode.value); const [agent, setAgent] = useState(store.selectedAgent.value);
  const save = () => { store.setPreference('provider', provider); store.setPreference('model', model); store.setPreference('effort', effort); store.setPreference('reasoning', reasoning); store.setPreference('agent', agent); store.saveSettings(token); };
  return <Overlay title="Settings" close={!store.authRequired.value}><div class="settings-field"><label class="settings-label" for="providerSelect">Provider</label><select class="settings-select" id="providerSelect" value={provider} onChange={(event) => { setProvider(event.currentTarget.value); void store.endpoints.models(event.currentTarget.value).then((data) => { store.models.value = (Array.isArray(data.models) ? data.models : []) as typeof store.models.value; }); }}><option value="">Auto (server default)</option>{store.providers.value.map((entry) => <option value={entry.id} key={entry.id}>{entry.name}</option>)}</select></div>
    <div class="settings-field"><label class="settings-label" for="modelSelect">Model</label><select class="settings-select" id="modelSelect" value={model} onChange={(event) => setModel(event.currentTarget.value)}><option value="">Auto (server default)</option>{store.models.value.map((entry) => <option value={entry.id} key={entry.id}>{entry.name || entry.id}</option>)}</select></div>
    <div class="settings-field"><label class="settings-label" for="effortSelect">Effort</label><select class="settings-select" id="effortSelect" value={effort} onChange={(event) => setEffort(event.currentTarget.value)}>{['', 'none', 'minimal', 'low', 'medium', 'high', 'xhigh', 'max'].map((value) => <option value={value} key={value}>{value || 'Auto (server default)'}</option>)}</select></div>
    <div class="settings-field"><label class="settings-label" for="reasoningModeSelect">Reasoning mode</label><select class="settings-select" id="reasoningModeSelect" value={reasoning} onChange={(event) => setReasoning(event.currentTarget.value)}><option value="standard">Standard</option><option value="pro">Pro</option></select></div>
    {store.config.agentNames.length > 1 && <div class="settings-field"><label class="settings-label" for="agentSelect">Agent</label><select class="settings-select" id="agentSelect" value={agent} onChange={(event) => setAgent(event.currentTarget.value)}><option value="">Default</option>{store.config.agentNames.map((name) => <option value={name} key={name}>{name}</option>)}</select></div>}
    <div class="settings-field"><label class="settings-label" for="authTokenInput">Bearer token</label><input id="authTokenInput" type="password" value={token} placeholder="paste your bearer token" autoComplete="off" onInput={(event) => setToken(event.currentTarget.value)} /></div>
    <div class="settings-field"><label class="settings-toggle"><span class="settings-label settings-label-inline">Show hidden sessions</span><input type="checkbox" checked={store.showHidden.value} onChange={(event) => { store.showHidden.value = event.currentTarget.checked; store.storage.setItem(store.keys.showHiddenSessions, event.currentTarget.checked ? '1' : '0'); void store.refreshSidebar(); }} /></label></div>
    <div class="settings-field"><label class="settings-toggle"><span class="settings-label settings-label-inline">Show widgets in sidebar</span><input type="checkbox" checked={store.showWidgets.value} onChange={(event) => { store.showWidgets.value = event.currentTarget.checked; store.storage.setItem(store.keys.showWidgetsSidebar, event.currentTarget.checked ? '1' : '0'); }} /></label></div>
    {store.config.vapidKey && <div class="settings-field"><button class="btn" disabled={store.notificationsEnabled.value} onClick={() => void store.enableNotifications()}>{store.notificationsEnabled.value ? 'Notifications enabled' : 'Enable notifications'}</button></div>}
    <div class="modal-actions">{!store.authRequired.value && <button class="btn" type="button" onClick={() => { store.modal.value = ''; }}>Cancel</button>}<button class="btn primary" type="button" onClick={save}>Save</button></div>
  </Overlay>;
}

function Rename() {
  const store = useStore(); const target = store.renameTarget.value; const [title, setTitle] = useState(target?.title || ''); const [detail, setDetail] = useState(''); const [loading, setLoading] = useState(false);
  return <Overlay title="Rename session"><p>Choose the label shown in the sidebar, or let AI suggest a better title.</p><div class="settings-field"><label class="settings-label">Session name</label><input autoFocus value={title} onInput={(event) => setTitle(event.currentTarget.value)} /></div>{detail && <div class="settings-field"><label class="settings-label">Detail</label><textarea value={detail} onInput={(event) => setDetail(event.currentTarget.value)} /></div>}<button class="btn rename-improve-btn" disabled={loading} onClick={() => { setLoading(true); void store.improveTitle().then((value) => { setTitle(value.title); setDetail(value.detail); }).finally(() => setLoading(false)); }}>{loading ? 'Improving…' : 'Improve title with AI'}</button><div class="modal-actions"><button class="btn" onClick={() => { store.modal.value = ''; }}>Cancel</button><button class="btn primary" onClick={() => void store.renameSession(title)}>Save</button></div></Overlay>;
}

function AskUser() {
  const store = useStore(); const prompt = store.askUser.value; const [answers, setAnswers] = useState<Record<number, string[]>>({}); const [custom, setCustom] = useState<Record<number, string>>({}); const [tab, setTab] = useState(0); const [error, setError] = useState(''); const [sending, setSending] = useState(false); if (!prompt) return null;
  const question = prompt.questions[tab];
  const validate = (item: typeof prompt.questions[number], index: number) => {
    const selected = answers[index] || []; const own = custom[index]?.trim();
    if (item.multi_select && !selected.length) throw new Error(`${item.header || `Question ${index + 1}`}: choose at least one option.`);
    if (!item.multi_select && !selected.length && !own) throw new Error(`${item.header || `Question ${index + 1}`}: choose or enter an answer.`);
    return { question_index: index, header: item.header, selected: own || selected.join(', '), selected_list: item.multi_select ? selected : undefined, is_custom: Boolean(own), is_multi_select: Boolean(item.multi_select) };
  };
  const submit = async (cancelled = false) => {
    setError(''); setSending(true);
    try { await store.answerAskUser(cancelled ? [] : prompt.questions.map(validate), cancelled); }
    catch (value) { setError(value instanceof Error ? value.message : String(value)); }
    finally { setSending(false); }
  };
  const dismiss = () => { if (tab > 0) setTab(tab - 1); else void submit(true); };
  const next = () => { try { validate(question, tab); setError(''); setTab(tab + 1); } catch (value) { setError(value instanceof Error ? value.message : String(value)); } };
  return <Overlay title={prompt.questions.length > 1 ? `Question ${tab + 1} of ${prompt.questions.length}` : 'Answer question'} close={false} onEscape={dismiss}><p>The agent needs your input to continue.</p>{prompt.questions.length > 1 && <div class="ask-user-steps">{prompt.questions.map((_item, index) => <button class={index === tab ? 'active' : index < tab ? 'completed' : ''} onClick={() => setTab(index)}>{index + 1}</button>)}</div>}<fieldset><legend>{question.header && <strong>{question.header}: </strong>}{question.question}</legend>{question.options?.map((option) => <label class="ask-user-option" key={option.label}><input type={question.multi_select ? 'checkbox' : 'radio'} name={`question-${tab}`} value={option.label} checked={(answers[tab] || []).includes(option.label)} onChange={(event) => { const current = answers[tab] || []; setAnswers({ ...answers, [tab]: question.multi_select ? event.currentTarget.checked ? [...current, option.label] : current.filter((value) => value !== option.label) : [option.label] }); setCustom({ ...custom, [tab]: '' }); }} /><span><strong>{option.label}</strong>{option.description && <small>{option.description}</small>}</span></label>)}{!question.multi_select && <label class="ask-user-custom"><span>Other</span><textarea placeholder="Type your answer…" value={custom[tab] || ''} onInput={(event) => { setCustom({ ...custom, [tab]: event.currentTarget.value }); setAnswers({ ...answers, [tab]: [] }); }} /></label>}</fieldset>{error && <div class="modal-error">{error}</div>}<div class="modal-actions"><button class="btn" disabled={sending} onClick={dismiss}>{tab > 0 ? 'Back' : sending ? 'Dismissing…' : 'Dismiss'}</button>{tab < prompt.questions.length - 1 ? <button class="btn primary" disabled={sending} onClick={next}>Next</button> : <button class="btn primary" disabled={sending} onClick={() => void submit()}>{sending ? 'Sending…' : 'Continue'}</button>}</div></Overlay>;
}

function Approval() {
  const store = useStore(); const prompt = store.approval.value; const options = prompt?.options || []; const deny = options.find((option) => option.choice === 'deny')?.index ?? options.at(-1)?.index ?? 0; const [choice, setChoice] = useState(options.find((option) => option.choice !== 'deny')?.index ?? 0); const [resume, setResume] = useState(false); const [error, setError] = useState(''); if (!prompt) return null;
  const decide = async (selected: number) => { try { await store.decideApproval(selected, resume); } catch (value) { setError(value instanceof Error ? value.message : String(value)); } };
  return <Overlay title={prompt.title || 'Access Request'} close={false} onEscape={() => void decide(deny)}>{prompt.intro && <div class="approval-intro">{prompt.intro}</div>}{prompt.path && <code class="approval-path">{prompt.path}</code>}<div class="approval-body">{prompt.body}</div>{options.filter((option) => option.choice !== 'deny').map((option) => <label class="approval-option"><input type="radio" name="approval" checked={choice === option.index} onChange={() => setChoice(option.index)} />{option.label || option.title || option.choice}</label>)}{prompt.resumeAutoAvailable && <label><input type="checkbox" checked={resume} onChange={(event) => setResume(event.currentTarget.checked)} /> Resume Guardian auto-approval</label>}{prompt.note && <div class="approval-note">{prompt.note}</div>}{error && <div class="modal-error">{error}</div>}<div class="modal-actions"><button class="btn" onClick={() => void decide(deny)}>Deny</button><button class="btn primary" onClick={() => void decide(choice)}>Approve</button></div></Overlay>;
}

function MCP() { const store = useStore(); const state = store.mcp.value; return <Overlay title="MCP servers"><p>Turn on configured servers for this chat. Changes save immediately.</p>{state.loading && <p>Loading…</p>}{state.error && <div class="modal-error">{state.error}</div>}<div class="mcp-server-list">{state.available.map((name) => <label class="mcp-server-row" key={name}><span>{name}</span><input type="checkbox" checked={state.enabled.includes(name)} disabled={store.streaming.value} onChange={() => void store.toggleMCP(name)} /></label>)}</div></Overlay>; }
function GoalModal() { const store = useStore(); const current = store.goal.value; const [objective, setObjective] = useState(current?.objective || ''); const [budget, setBudget] = useState(current?.token_budget ? String(current.token_budget) : ''); const save = () => void store.saveGoal({ objective: objective.trim(), token_budget: Number(budget) || undefined, status: 'active' }); return <Overlay title="Session goal"><p>Set a persistent objective the agent can keep pursuing across automatic continuations.</p><label class="settings-label">Objective</label><textarea class="goal-objective-input" rows={5} value={objective} onInput={(event) => setObjective(event.currentTarget.value)} /><label class="settings-label">Token budget (optional)</label><input type="number" min={1} value={budget} onInput={(event) => setBudget(event.currentTarget.value)} /><div class="modal-actions goal-actions">{current && <button class="btn" onClick={() => void store.saveGoal({ action: 'clear' })}>Clear</button>}{current?.status === 'paused' ? <button class="btn" onClick={() => void store.saveGoal({ action: 'resume' })}>Resume</button> : current && <button class="btn" onClick={() => void store.saveGoal({ action: 'pause' })}>Pause</button>}<button class="btn primary" disabled={!objective.trim()} onClick={save}>Set goal</button></div></Overlay>; }
function Widgets() { const store = useStore(); return <Overlay title="Widgets"><div class="widgets-modal-list">{store.widgets.value.map((widget) => <a class="widget-row" key={widget.id} href={widget.url} title={widget.description}><span>{widget.name}{widget.state && widget.state !== 'stopped' ? ` · ${widget.state}` : ''}</span><span>→</span></a>)}</div></Overlay>; }

function BranchTree() { const store = useStore(); const tree = store.branchTree.value; const nodes = tree ? (Array.isArray(tree.branch_points) ? tree.branch_points : Array.isArray(tree.nodes) ? tree.nodes : Array.isArray(tree.branches) ? tree.branches : []) as Array<Record<string, unknown>> : []; const [focus, setFocus] = useState(''); return <Overlay title="Conversation tree" wide><p>Switch paths or start a new one from an earlier turn.</p><div class="branch-tree-list">{nodes.map((node, index) => <div class="branch-tree-row" key={String(node.id || index)}><div><strong>{String(node.title || node.label || `Path ${index + 1}`)}</strong><small>{String(node.summary || '')}</small></div>{node.session_id && <button onClick={() => { const session = store.sessions.value.find((entry) => entry.id === node.session_id); if (session) void store.selectSession(session); store.modal.value = ''; }}>Open</button>}<button onClick={() => void store.branchFrom(String(node.message_id || node.id || ''), 'clean')}>Clean branch</button><button onClick={() => void store.branchFrom(String(node.message_id || node.id || ''), 'notes')}>Bring notes</button><input aria-label="Focused branch context" placeholder="Focus context…" value={focus} onInput={(event) => setFocus(event.currentTarget.value)} /><button disabled={!focus.trim()} onClick={() => void store.branchFrom(String(node.message_id || node.id || ''), 'focused', focus)}>Focused</button></div>)}</div><p class="branch-tree-note">Branches rewind conversation context only. Filesystem and tool side effects are not undone.</p></Overlay>; }

function Worktrees() {
  const store = useStore(); const [name, setName] = useState(''); const [selected, setSelected] = useState<Record<string, unknown> | null>(null); const [diff, setDiff] = useState(''); const [branch, setBranch] = useState(''); const [error, setError] = useState(''); const draft = store.draftActive.value;
  const dir = String(selected?.dir || selected?.path || '');
  return <Overlay title="Worktrees" wide>{store.worktreeError.value && <div class="modal-error">{store.worktreeError.value}<button onClick={() => void store.loadWorktrees()}>Retry</button></div>}<div class="worktree-list"><button class="worktree-row" onClick={() => draft ? store.chooseDraftWorktree('') : setSelected({ root: true })}><strong>Project root</strong></button>{store.worktrees.value.map((worktree, index) => <button class={`worktree-row ${selected === worktree ? 'selected' : ''}`} key={String(worktree.dir || worktree.path || index)} onClick={() => { if (draft) store.chooseDraftWorktree(String(worktree.dir || worktree.path || '')); else setSelected(worktree); }}><strong>{String(worktree.name || worktree.branch || 'worktree')}</strong><small>{String(worktree.dir || worktree.path || '')}</small>{Array.isArray(worktree.in_use) && worktree.in_use.length > 0 && <span>In use</span>}</button>)}</div>{selected && !draft && dir && <div class="worktree-actions"><button onClick={() => void store.worktreeDiff(dir).then(setDiff).catch((value) => setError(String(value)))}>View diff</button><button onClick={() => void store.mergeWorktree(dir).catch((value) => setError(String(value)))}>Merge</button><input placeholder="Branch name" value={branch} onInput={(event) => setBranch(event.currentTarget.value)} /><button disabled={!branch.trim()} onClick={() => void store.promoteWorktree(dir, branch).catch((value) => setError(String(value)))}>Promote</button><button class="danger" onClick={() => void store.removeWorktree(dir).catch(async (value) => { if (value instanceof Error && confirm(`${value.message}\nForce remove?`)) await store.removeWorktree(dir, true); else setError(String(value)); })}>Remove</button>{diff && <pre>{diff}</pre>}{error && <div class="modal-error">{error}</div>}</div>}<form onSubmit={(event) => { event.preventDefault(); if (name.trim()) void store.createWorktree(name.trim()).then(() => setName('')); }}><input placeholder="New worktree name" value={name} onInput={(event) => setName(event.currentTarget.value)} /><button class="btn primary" type="submit">Create</button></form></Overlay>;
}
function Skills() { const store = useStore(); const [selected, setSelected] = useState(''); const [args, setArgs] = useState(''); return <Overlay title="Skills"><div class="skills-list">{store.skills.value.map((skill) => { const name = String(skill.name || skill.id || ''); return <button class={`skill-row ${selected === name ? 'selected' : ''}`} key={name} onClick={() => setSelected(name)}><strong>{name}</strong><small>{String(skill.description || '')}</small></button>; })}</div>{selected && <form onSubmit={(event) => { event.preventDefault(); void store.invokeSkill(selected, args); }}><label class="settings-label">Arguments for {selected}</label><textarea value={args} onInput={(event) => setArgs(event.currentTarget.value)} /><button class="btn primary" type="submit">Run skill</button></form>}</Overlay>; }

function ProjectPicker() {
  const store = useStore(); const target = store.projectTarget.value; const [path, setPath] = useState(''); const [name, setName] = useState(''); const [matches, setMatches] = useState<Array<Record<string, unknown>>>([]); const [error, setError] = useState('');
  const create = async () => { try { const data = await store.endpoints.createProject({ path: path.trim(), name: name.trim() }); const project = data.project && typeof data.project === 'object' ? data.project as Record<string, unknown> : null; const id = String(data.id || project?.id || data.existing_project_id || ''); await store.refreshSidebar(); if (target) await store.assignProject(id); else await store.startProjectChat(id); store.modal.value = ''; } catch (value) { setError(value instanceof Error ? value.message : String(value)); } };
  return <Overlay title={target ? 'Move to project' : 'Add project'}><div class="project-picker-list">{target && <button class="project-picker-row" onClick={() => void store.assignProject('')}><strong>No project</strong></button>}{store.projects.value.filter((project) => !project.archived).map((project) => <button class="project-picker-row" key={project.id} onClick={() => target ? void store.assignProject(project.id) : void store.startProjectChat(project.id)}><strong>{project.name}</strong><small>{project.path}</small></button>)}</div><form class="project-create-form" onSubmit={(event) => { event.preventDefault(); if (path.trim()) void create(); }}><h3>Create project</h3><input aria-label="Project path" placeholder="/path/to/project" value={path} autoCapitalize="none" autoCorrect="off" spellcheck={false} onInput={(event) => { setPath(event.currentTarget.value); void store.endpoints.projectDirectories(event.currentTarget.value).then((data) => setMatches(Array.isArray(data.directories) ? data.directories as Array<Record<string, unknown>> : [])).catch(() => setMatches([])); }} />{matches.map((match) => <button type="button" onClick={() => setPath(String(match.path || ''))}>{String(match.path || '')}</button>)}<input aria-label="Project name" placeholder="Name (optional)" value={name} onInput={(event) => setName(event.currentTarget.value)} />{error && <div class="modal-error">{error}</div>}<button class="btn primary" type="submit">{target ? 'Create and move' : 'Create project'}</button></form></Overlay>;
}

export function SideQuestion() {
  const store = useStore(); const state = store.sideQuestion.value; const [question, setQuestion] = useState('');
  useEffect(() => { if (!state.visible) return; const escape = (event: KeyboardEvent) => { if (event.key === 'Escape') void store.closeSideQuestion(); }; addEventListener('keydown', escape); return () => removeEventListener('keydown', escape); }, [state.visible, store]);
  if (!state.visible) return null; return <div class="side-question-overlay" role="dialog" aria-modal="true" aria-label="Side question"><div class="side-question-panel"><div class="side-question-header"><strong>Side question</strong><button class="icon-btn" aria-label="Close side question" onClick={() => void store.closeSideQuestion()}>✕</button></div>{state.history.map((entry, index) => <div class="side-question-transcript" key={index}><div class="side-question-user">{entry.question}</div><div class="side-question-assistant">{entry.response}</div></div>)}{state.response && !state.history.some((entry) => entry.response === state.response) && <div class="side-question-assistant">{state.response}</div>}{state.error && <div class="side-question-error">{state.error}</div>}<form class="side-question-composer" onSubmit={(event) => { event.preventDefault(); if (!question.trim()) return; void store.askSideQuestion(question); setQuestion(''); }}><input autoFocus value={question} placeholder="Ask a follow-up…" onInput={(event) => setQuestion(event.currentTarget.value)} /><button type="submit" disabled={state.running}>{state.running ? '…' : '↑'}</button></form></div></div>;
}

export function Modals() { const store = useStore(); switch (store.modal.value) { case 'settings': return <Settings />; case 'rename': return <Rename />; case 'project': return <ProjectPicker />; case 'ask-user': return <AskUser />; case 'approval': return <Approval />; case 'mcp': return <MCP />; case 'goal': return <GoalModal />; case 'widgets': return <Widgets />; case 'skills': return <Skills />; case 'branch': return <BranchTree />; case 'worktrees': return <Worktrees />; default: return null; } }
