import { useEffect, useRef, useState } from 'preact/hooks';
import { useStore } from '../app/context';
import type { DiffFile, DiffLine } from '../domain/types';
import { clampDiffWidth, fileKind, inlineEmphasis, unifiedPatchForFile } from '../domain/diff';
import { copyText } from '../platform/browser';
import { rebaseHubAssetURL } from '../app/config';
import { Icon } from './Icon';

function Line({ line, emphasis, commentKey, commenting, body, onComment, onBody, onCancel, onSubmit }: { line: DiffLine; emphasis?: [number, number]; commentKey: string; commenting: boolean; body: string; onComment: (key: string) => void; onBody: (value: string) => void; onCancel: () => void; onSubmit: (event: SubmitEvent) => void }) {
  const number = line.kind === 'delete' ? line.oldLine : line.newLine;
  const content = emphasis && emphasis[1] > emphasis[0] ? <>{line.content.slice(0, emphasis[0])}<mark class="diff-word">{line.content.slice(emphasis[0], emphasis[1])}</mark>{line.content.slice(emphasis[1])}</> : line.content;
  const kind = line.kind === 'add' ? 'add' : line.kind === 'delete' ? 'del' : line.kind === 'hunk' ? 'hunk' : 'ctx';
  return <div class={`diff-row ${kind}`} data-commentable={Boolean(number && line.kind !== 'hunk')}><span class="diff-ln">{line.oldLine || ''}</span><span class="diff-ln">{line.newLine || ''}</span><code class="diff-code">{line.kind === 'add' ? '+' : line.kind === 'delete' ? '−' : line.kind === 'hunk' ? '' : ' '}{content}</code>
    {number && line.kind !== 'hunk' && <button class="diff-comment-affordance" type="button" aria-label={`Comment on line ${number}`} aria-expanded={commenting} onMouseDown={(event) => { event.preventDefault(); event.stopPropagation(); onComment(commentKey); }} onKeyDown={(event) => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); event.stopPropagation(); onComment(commentKey); } }}><Icon name="add" /></button>}
    {commenting && <form class="diff-comment-panel diff-comment-editor" onSubmit={onSubmit}><textarea autoFocus aria-label="Inline comment" value={body} onInput={(event) => onBody(event.currentTarget.value)} /><div class="diff-comment-editor-actions"><button class="diff-comment-cancel" type="button" onClick={onCancel}>Cancel</button><button class="diff-comment-send" type="submit">Queue</button></div></form>}
  </div>;
}

function File({ file }: { file: DiffFile }) {
  const store = useStore(); const [limit, setLimit] = useState(500); const [commenting, setCommenting] = useState(''); const [body, setBody] = useState(''); const lines = file.lines || []; const kind = fileKind(file);
  const emphasis = new Map<number, [number, number]>();
  for (let index = 0; index + 1 < lines.length; index += 1) if (lines[index].kind === 'delete' && lines[index + 1].kind === 'add') { const ranges = inlineEmphasis(lines[index].content, lines[index + 1].content); emphasis.set(index, ranges.old); emphasis.set(index + 1, ranges.new); }
  const submitComment = (event: SubmitEvent, line: DiffLine) => { event.preventDefault(); const number = line.kind === 'delete' ? line.oldLine : line.newLine; if (!body.trim() || !number) return; store.queueDiffComment({ path: file.path, side: line.kind === 'delete' ? 'old' : 'new', line: number, body: body.trim(), scope: store.diff.value.scope, context: line.content, fileChangeSeq: file.snapshotSeq || file.sequence || 0 }); setBody(''); setCommenting(''); };
  return <section class={`diff-file diff-file-${kind}`}>
    <div class={`diff-file-row ${file.expanded ? 'expanded' : ''}`}>
      <button class="diff-file-toggle" type="button" aria-label={`Toggle diff for ${file.path}`} aria-expanded={file.expanded} onClick={() => void store.expandDiff(file)}><span class="diff-chevron"><Icon name="chevron-right" /></span><span class="diff-file-path">{file.path}</span></button>
      <span class="diff-file-counts"><span class="diff-count-add">+{file.additions || 0}</span><span class="diff-count-del">−{file.deletions || 0}</span></span>
      <span class="diff-file-actions"><button class="diff-action-btn" type="button" aria-label={`Copy path ${file.path}`} onClick={() => void copyText(file.path)}><Icon name="copy" /></button>{file.lines && <button class="diff-action-btn diff-patch-action" type="button" aria-label={`Copy patch ${file.path}`} onClick={() => void copyText(unifiedPatchForFile(file))}>Patch</button>}</span>
    </div>
    {file.expanded && <div class="diff-file-body">{file.loading && <div class="diff-loading">Loading…</div>}{file.error && <div class="diff-error">{file.error}<button class="diff-retry" onClick={() => void store.expandDiff({ ...file, lines: undefined })}>Retry</button></div>}{file.truncated && <div class="diff-error">This file was too large to retain a text diff.</div>}{file.image ? <div class={`diff-image-comparison diff-image-${kind}`}>{kind !== 'add' && file.beforeURL && <figure class="diff-image-side"><figcaption class="diff-image-label">Before</figcaption><img class="diff-image-preview" src={rebaseHubAssetURL(store.config, file.beforeURL)} alt={`Before ${file.path}`} /></figure>}{kind !== 'delete' && file.afterURL && <figure class="diff-image-side"><figcaption class="diff-image-label">After</figcaption><img class="diff-image-preview" src={rebaseHubAssetURL(store.config, file.afterURL)} alt={`After ${file.path}`} /></figure>}</div> : <><div class={`diff-rows diff-rows-kind-${kind}`}>{lines.slice(0, limit).map((line, index) => { const key = `${line.kind}-${line.oldLine || 0}-${line.newLine || 0}-${index}`; return <Line key={key} line={line} emphasis={emphasis.get(index)} commentKey={key} commenting={commenting === key} body={body} onComment={(next) => { setBody(''); setCommenting(next); }} onBody={setBody} onCancel={() => { setBody(''); setCommenting(''); }} onSubmit={(event) => submitComment(event, line)} />; })}{lines.length > limit && <button class="diff-show-more" onClick={() => setLimit((value) => Math.min(lines.length, value + 500))}>Show {Math.min(500, lines.length - limit)} more lines</button>}</div>{!file.truncated && lines.length > 0 && (file.context || 3) < Math.max(file.oldLineCount || 0, file.newLineCount || 0) && <div class="diff-bulk-toggle"><button class="diff-hunk-expand" type="button" onClick={() => void store.expandDiff(file, Math.min(100_000, Math.max(12, (file.context || 3) * 4)))}>Show more context</button><button class="diff-hunk-expand" type="button" onClick={() => void store.expandDiff(file, 100_000)}>Show full file</button></div>}</>}</div>}
  </section>;
}

export function DiffSidebar() {
  const store = useStore(); const state = store.diff.value; const aside = useRef<HTMLElement>(null);
  useEffect(() => { if (!state.open) return; const escape = (event: KeyboardEvent) => { if (event.key !== 'Escape') return; const target = event.target as HTMLInputElement; if (target?.matches('input[type="search"]') && target.value) { store.diff.value = { ...store.diff.peek(), filter: '' }; target.value = ''; } else store.diff.value = { ...store.diff.peek(), maximized: false, open: state.maximized ? true : false }; }; addEventListener('keydown', escape); return () => removeEventListener('keydown', escape); }, [state.open, state.maximized, store]);
  if (!state.open) return null; const files = state.files.filter((file) => file.path.toLowerCase().includes(state.filter.toLowerCase())); const comments = state.comments.filter((comment) => !comment.sessionId || comment.sessionId === state.sessionId);
  const startResize = (event: PointerEvent) => { const startX = event.clientX; const startWidth = state.width; const move = (next: PointerEvent) => store.resizeDiff(clampDiffWidth(startWidth + startX - next.clientX, innerWidth)); const finish = () => { removeEventListener('pointermove', move); removeEventListener('pointerup', finish); }; addEventListener('pointermove', move); addEventListener('pointerup', finish, { once: true }); };
  return <aside ref={aside} class={`diff-sidebar open ${state.maximized ? 'maximized' : ''}`} id="diffSidebar" aria-label="Session file changes" style={state.maximized ? undefined : { width: `${state.width}px` }}><div class="diff-resize-handle" role="separator" aria-label="Resize changes panel" aria-orientation="vertical" tabIndex={0} onPointerDown={startResize} onDblClick={() => store.resizeDiff(420)} />
    <div class="diff-sidebar-header"><select class="diff-scope-select" id="diffScopeSelect" aria-label="Change scope" value={state.scope} onChange={(event) => { store.diff.value = { ...state, scope: event.currentTarget.value }; void store.loadDiff(); }}><option value="last_turn">Last turn</option><option value="last_3_turns">Last 3 turns</option><option value="uncommitted">Uncommitted</option><option value="unstaged">Unstaged</option><option value="staged">Staged</option></select><span class="diff-sidebar-totals"><span class="diff-sidebar-totals-add">+{state.files.reduce((sum, file) => sum + (file.additions || 0), 0)}</span><span class="diff-sidebar-totals-del">−{state.files.reduce((sum, file) => sum + (file.deletions || 0), 0)}</span></span><button class="icon-btn diff-sidebar-maximize" type="button" aria-label={state.maximized ? 'Restore changes' : 'Maximize changes'} onClick={() => { store.diff.value = { ...state, maximized: !state.maximized }; }}><Icon name={state.maximized ? 'restore' : 'expand'} /></button><button class="icon-btn diff-sidebar-close" type="button" aria-label="Hide changes" onClick={() => { store.diff.value = { ...state, open: false }; }}><Icon name="close" /></button></div>
    {(state.files.length > 8 || state.filter) && <div class="diff-filter-row"><input class="diff-filter-input" type="search" placeholder="Filter files…" aria-label="Filter changed files" value={state.filter} onInput={(event) => { store.diff.value = { ...state, filter: event.currentTarget.value }; }} /></div>}
    <div class="diff-file-list" aria-label="Changed files">{state.loading && <div class="diff-loading">Loading changes…</div>}{state.error && <div class="diff-error">{state.error}<button class="diff-retry" onClick={() => void store.loadDiff()}>Retry</button></div>}{files.map((file) => <File key={file.path} file={file} />)}{!state.loading && !state.error && !files.length && <div class="diff-empty">No file changes in this scope.</div>}</div>
    <div class="diff-queue-status" role="status">{comments.length ? `${comments.length} inline comment${comments.length === 1 ? '' : 's'} queued.` : 'No inline comments queued.'}</div>{comments.length > 0 && <div class="diff-queue-bar"><span class="diff-queue-count">{comments.length} queued</span><button class="diff-queue-discard" type="button" onClick={() => { const remaining = state.comments.filter((comment) => comment.sessionId && comment.sessionId !== state.sessionId); store.diff.value = { ...state, comments: remaining }; }}>Discard</button><button class="diff-queue-send" type="button" onClick={() => void store.sendDiffComments()}>Send comments</button></div>}
  </aside>;
}

export function PlanSurface() {
  const store = useStore(); const plan = store.currentPlan.value; if (!plan || !store.planOpen.value) return null;
  return <aside class="plan-panel open" id="planPanel" role="complementary" aria-labelledby="planPanelTitle"><div class="plan-surface-header"><h2 id="planPanelTitle">Current plan</h2><span class="plan-surface-progress">{plan.plan.filter((step) => step.status === 'completed').length}/{plan.plan.length}</span><button class="icon-btn" type="button" aria-label="Close current plan" onClick={() => { store.planOpen.value = false; }}><Icon name="close" /></button></div><div class="plan-surface-body">{plan.explanation && <p class="current-plan-explanation">{plan.explanation}</p>}<div class="current-plan-checklist">{plan.plan.map((step, index) => <div class={`current-plan-step current-plan-step-${step.status}`} key={`${index}-${step.step}`}><span class="current-plan-step-marker">{step.status === 'completed' ? <Icon name="check" /> : step.status === 'in_progress' ? '●' : '○'}</span><div class="current-plan-step-content"><div class="current-plan-step-text">{step.step}</div><div class="current-plan-step-state">{step.status.replace('_', ' ')}</div></div></div>)}</div></div></aside>;
}
