import type { APIClient } from './client';
import type { DiffComment, Goal } from '../domain/types';

const encoded = (value: string): string => encodeURIComponent(value);
export const endpoints = (api: APIClient) => ({
  capabilities: () => api.get<Record<string, unknown>>('/v1/capabilities'),
  providers: () => api.get<Record<string, unknown>>('/v1/providers'),
  models: (provider = '', signal?: AbortSignal) => api.get<Record<string, unknown>>(`/v1/models${provider ? `?provider=${encoded(provider)}` : ''}`, signal),
  sidebar: (hidden: boolean) => api.get<Record<string, unknown>>(`/v1/sidebar?per_project=12&include_archived_projects=1&include_archived_sessions=${hidden ? '1' : '0'}`),
  projectSessions: (projectId: string, cursor: string, hidden: boolean) => api.get<Record<string, unknown>>(`/v1/sessions?project_id=${encoded(projectId)}&cursor=${encoded(cursor)}&limit=12&include_archived=${hidden ? '1' : '0'}`),
  noProjectSessions: (cursor: string, hidden: boolean) => api.get<Record<string, unknown>>(`/v1/sessions?no_project=1&cursor=${encoded(cursor)}&limit=30&include_archived=${hidden ? '1' : '0'}`),
  sessionStatus: (selected = '') => api.get<Record<string, unknown>>(`/v1/sessions/status${selected ? `?selected_session=${encoded(selected)}` : ''}`),
  searchSessions: (query: string, hidden = false, categories: string[] = ['all'], signal?: AbortSignal) => {
    const params = new URLSearchParams({ q: query, limit: '30' });
    if (hidden) params.set('include_archived', '1');
    if (!categories.includes('all')) params.set('categories', categories.join(','));
    return api.get<Record<string, unknown>>(`/v1/sessions/search?${params}`, signal);
  },
  sessions: (query = '') => api.get<Record<string, unknown>>(`/v1/sessions${query ? `?${query}` : ''}`),
  selectedSession: (id: string) => api.get<Record<string, unknown>>(`/v1/sessions?selected_only=1&include_transcript=1&include_widget_status=1&selected_session=${encoded(id)}`),
  sessionState: (id: string, signal?: AbortSignal) => api.get<Record<string, unknown>>(`/v1/sessions/${encoded(id)}/state`, signal),
  transcript: (id: string, signal?: AbortSignal) => api.get<Record<string, unknown>>(`/v1/sessions/${encoded(id)}/transcript`, signal),
  transcriptBodies: (id: string, ids: number[], signal?: AbortSignal) => api.get<Record<string, unknown>>(`/v1/sessions/${encoded(id)}/transcript/bodies?ids=${ids.join(',')}`, signal),
  createResponse: (body: unknown, sessionId: string, requestId: string, signal?: AbortSignal) => api.request('/v1/responses', { method: 'POST', signal, headers: { ...(sessionId ? { 'X-Term-LLM-Session-ID': sessionId } : {}), 'Idempotency-Key': requestId, 'X-Term-LLM-Request-ID': requestId }, body: JSON.stringify(body) }, { policy: 'idempotent-mutation', retries: 2, timeoutMs: 0, auth: 'session' }),
  response: (id: string, signal?: AbortSignal) => api.get<Record<string, unknown>>(`/v1/responses/${encoded(id)}`, signal),
  responseEvents: (id: string, after: number, signal: AbortSignal) => api.request(`/v1/responses/${encoded(id)}/events?after=${after}`, { signal, headers: { Accept: 'text/event-stream' } }, { policy: 'stream', retries: 0, timeoutMs: 0, auth: 'session' }),
  cancelResponse: (id: string) => api.post<Record<string, unknown>>(`/v1/responses/${encoded(id)}/cancel`, {}, 'idempotent-mutation', { 'Idempotency-Key': `cancel_${id}` }),
  interrupt: (sessionId: string, body: unknown, interjectionId: string) => api.json(`/v1/sessions/${encoded(sessionId)}/interrupt`, { method: 'POST', headers: { 'Idempotency-Key': `interrupt_${interjectionId}` }, body: JSON.stringify(body) }, { policy: 'idempotent-mutation', auth: 'session' }),
  deleteInterrupt: (sessionId: string, interjectionId: string) => api.delete(`/v1/sessions/${encoded(sessionId)}/interjections/${encoded(interjectionId)}`),
  patchSession: (id: string, body: unknown) => api.patch(`/v1/sessions/${encoded(id)}`, body),
  deleteSession: (id: string) => api.delete(`/v1/sessions/${encoded(id)}`),
  refineTitle: (id: string) => api.post<Record<string, unknown>>(`/v1/sessions/${encoded(id)}/title/refine`, {}),
  setProject: (id: string, projectId: string) => api.post(`/v1/sessions/${encoded(id)}/project`, { project_id: projectId }, 'idempotent-mutation', { 'Idempotency-Key': `project_${id}_${projectId || 'none'}` }),
  projects: (query = '') => api.get<Record<string, unknown>>(`/v1/projects${query ? `?${query}` : ''}`),
  createProject: (body: unknown) => api.post<Record<string, unknown>>('/v1/projects', body),
  patchProject: (id: string, body: unknown) => api.patch(`/v1/projects/${encoded(id)}`, body),
  projectDirectories: (query: string) => api.get<Record<string, unknown>>(`/v1/project-directories?q=${encoded(query)}`),
  runtime: (id: string, operation: string, body: unknown) => api.post(`/v1/sessions/${encoded(id)}/runtime/${operation}`, body, 'idempotent-mutation', { 'Idempotency-Key': `runtime_${id}_${operation}_${JSON.stringify(body)}` }),
  compact: (id: string) => api.post(`/v1/sessions/${encoded(id)}/runtime/compact`, {}),
  mutateTranscript: (id: string, operation: 'undo' | 'redo', body: unknown) => api.post<Record<string, unknown>>(`/v1/sessions/${encoded(id)}/runtime/${operation}`, body),
  goal: (id: string, body: Goal | { action: string }) => api.post(`/v1/sessions/${encoded(id)}/runtime/goal`, body, 'idempotent-mutation', { 'Idempotency-Key': `goal_${id}_${JSON.stringify(body)}` }),
  getMCP: (id: string) => api.get<Record<string, unknown>>(`/v1/sessions/${encoded(id)}/mcp`),
  setMCP: (id: string, enabled: string[]) => api.patch(`/v1/sessions/${encoded(id)}/mcp`, { enabled }),
  askUser: (id: string, body: unknown) => api.post(`/v1/sessions/${encoded(id)}/ask_user`, body),
  approval: (id: string, body: unknown) => api.post(`/v1/sessions/${encoded(id)}/approval`, body),
  sideQuestionState: (id: string) => api.get<Record<string, unknown>>(`/api/sessions/${encoded(id)}/side-question`),
  startSideQuestion: (id: string, question: string) => api.request(`/api/sessions/${encoded(id)}/side-question`, { method: 'POST', body: JSON.stringify({ question }) }, { policy: 'mutation', timeoutMs: 0, auth: 'session' }),
  cancelSideQuestion: (id: string) => api.request(`/api/sessions/${encoded(id)}/side-question/active`, { method: 'DELETE' }, 'idempotent-mutation'),
  tree: (id: string, signal?: AbortSignal) => api.get<Record<string, unknown>>(`/v1/sessions/${encoded(id)}/tree`, signal),
  branch: (id: string, body: unknown) => api.post<Record<string, unknown>>(`/v1/sessions/${encoded(id)}/branches`, body),
  pathNotes: (id: string, body: unknown) => api.post<Record<string, unknown>>(`/v1/sessions/${encoded(id)}/path-notes`, body),
  skills: (id: string) => api.get<Record<string, unknown>>(`/v1/sessions/${encoded(id)}/skills`),
  invokeSkill: (id: string, body: unknown, key: string) => api.post<Record<string, unknown>>(`/v1/sessions/${encoded(id)}/skills/invoke`, body, 'idempotent-mutation', { 'Idempotency-Key': `skill_${key}` }),
  skillRun: (id: string, runId: string) => api.get<Record<string, unknown>>(`/v1/sessions/${encoded(id)}/skill-runs/${encoded(runId)}`),
  cancelSkillRun: (id: string, runId: string) => api.delete(`/v1/sessions/${encoded(id)}/skill-runs/${encoded(runId)}`),
  fileChanges: (id: string, scope: string) => api.get<Record<string, unknown>>(`/v1/sessions/${encoded(id)}/file-changes${scope ? `?scope=${encoded(scope)}` : ''}`),
  fileDiff: (id: string, path: string, scope: string, context = 0) => api.get<Record<string, unknown>>(`/v1/sessions/${encoded(id)}/file-changes/diff?path=${encoded(path)}&scope=${encoded(scope)}${context ? `&context=${context}` : ''}`),
  diffComments: (id: string, comments: DiffComment[]) => api.post(`/v1/sessions/${encoded(id)}/diff-comments`, { comments }),
  legacyWorktrees: () => api.get<Record<string, unknown>>('/v1/worktrees'),
  projectWorktrees: (id: string) => api.get<Record<string, unknown>>(`/v1/projects/${encoded(id)}/worktrees`),
  createProjectWorktree: (id: string, body: unknown) => api.post<Record<string, unknown>>(`/v1/projects/${encoded(id)}/worktrees`, body),
  worktreeDiff: (id: string, dir: string) => api.get<Record<string, unknown>>(`/v1/projects/${encoded(id)}/worktrees/diff?dir=${encoded(dir)}`),
  mergeWorktree: (id: string, dir: string) => api.post<Record<string, unknown>>(`/v1/projects/${encoded(id)}/worktrees/merge`, { dir }),
  promoteWorktree: (id: string, dir: string, branch: string) => api.post<Record<string, unknown>>(`/v1/projects/${encoded(id)}/worktrees/promote`, { dir, branch }),
  removeWorktree: (id: string, dir: string, force = false) => api.delete<Record<string, unknown>>(`/v1/projects/${encoded(id)}/worktrees?dir=${encoded(dir)}${force ? '&force=1' : ''}`),
  transcribe: (body: FormData) => api.post<Record<string, unknown>>('/v1/transcribe', body),
  pushSubscribe: (body: unknown) => api.post('/v1/push/subscribe', body, 'idempotent-mutation', { 'Idempotency-Key': 'push_subscription' }),
  widgetStatus: () => api.json<Record<string, unknown>>('/admin/widgets/status', {}, { policy: 'safe-read', auth: 'ignore' }),
  hubNodes: (absoluteURL: string, signal?: AbortSignal) => api.json<Record<string, unknown>>(absoluteURL, { signal }, { policy: 'safe-read', auth: 'ignore', retries: 0, timeoutMs: 10_000 }),
});

export type Endpoints = ReturnType<typeof endpoints>;
