import highlight from 'highlight.js/lib/core';
import { definer as terraform } from '@taga3s/highlightjs-terraform';
import javascript from 'highlight.js/lib/languages/javascript';
import typescript from 'highlight.js/lib/languages/typescript';
import json from 'highlight.js/lib/languages/json';
import bash from 'highlight.js/lib/languages/bash';
import go from 'highlight.js/lib/languages/go';
import plaintext from 'highlight.js/lib/languages/plaintext';
import xml from 'highlight.js/lib/languages/xml';
import python from 'highlight.js/lib/languages/python';
import ruby from 'highlight.js/lib/languages/ruby';
import rust from 'highlight.js/lib/languages/rust';
import yaml from 'highlight.js/lib/languages/yaml';
import markdown from 'highlight.js/lib/languages/markdown';
import cpp from 'highlight.js/lib/languages/cpp';
import c from 'highlight.js/lib/languages/c';
import csharp from 'highlight.js/lib/languages/csharp';
import css from 'highlight.js/lib/languages/css';
import java from 'highlight.js/lib/languages/java';
import kotlin from 'highlight.js/lib/languages/kotlin';
import php from 'highlight.js/lib/languages/php';
import sql from 'highlight.js/lib/languages/sql';
import swift from 'highlight.js/lib/languages/swift';
import scss from 'highlight.js/lib/languages/scss';
import less from 'highlight.js/lib/languages/less';
import dockerfile from 'highlight.js/lib/languages/dockerfile';
import makefile from 'highlight.js/lib/languages/makefile';
import lua from 'highlight.js/lib/languages/lua';
import powershell from 'highlight.js/lib/languages/powershell';
import ini from 'highlight.js/lib/languages/ini';
import properties from 'highlight.js/lib/languages/properties';
import graphql from 'highlight.js/lib/languages/graphql';
import protobuf from 'highlight.js/lib/languages/protobuf';
import dart from 'highlight.js/lib/languages/dart';
import scala from 'highlight.js/lib/languages/scala';
import r from 'highlight.js/lib/languages/r';
import elixir from 'highlight.js/lib/languages/elixir';
import erlang from 'highlight.js/lib/languages/erlang';
import haskell from 'highlight.js/lib/languages/haskell';
import objectivec from 'highlight.js/lib/languages/objectivec';
import cmake from 'highlight.js/lib/languages/cmake';
import nix from 'highlight.js/lib/languages/nix';
import nginx from 'highlight.js/lib/languages/nginx';
import apache from 'highlight.js/lib/languages/apache';
import perl from 'highlight.js/lib/languages/perl';
import clojure from 'highlight.js/lib/languages/clojure';
import fsharp from 'highlight.js/lib/languages/fsharp';
import ocaml from 'highlight.js/lib/languages/ocaml';
import julia from 'highlight.js/lib/languages/julia';
import matlab from 'highlight.js/lib/languages/matlab';
import fortran from 'highlight.js/lib/languages/fortran';
import groovy from 'highlight.js/lib/languages/groovy';
import gradle from 'highlight.js/lib/languages/gradle';
import latex from 'highlight.js/lib/languages/latex';
import handlebars from 'highlight.js/lib/languages/handlebars';
import django from 'highlight.js/lib/languages/django';
import twig from 'highlight.js/lib/languages/twig';
import erb from 'highlight.js/lib/languages/erb';
import wasm from 'highlight.js/lib/languages/wasm';
import x86asm from 'highlight.js/lib/languages/x86asm';
import armasm from 'highlight.js/lib/languages/armasm';
import verilog from 'highlight.js/lib/languages/verilog';
import vhdl from 'highlight.js/lib/languages/vhdl';
import glsl from 'highlight.js/lib/languages/glsl';
import awk from 'highlight.js/lib/languages/awk';
import tcl from 'highlight.js/lib/languages/tcl';
import vim from 'highlight.js/lib/languages/vim';
import scheme from 'highlight.js/lib/languages/scheme';
import lisp from 'highlight.js/lib/languages/lisp';
import prolog from 'highlight.js/lib/languages/prolog';
import elm from 'highlight.js/lib/languages/elm';
import crystal from 'highlight.js/lib/languages/crystal';
import nim from 'highlight.js/lib/languages/nim';
import ada from 'highlight.js/lib/languages/ada';
import vbnet from 'highlight.js/lib/languages/vbnet';
import coffeescript from 'highlight.js/lib/languages/coffeescript';
import diff from 'highlight.js/lib/languages/diff';

highlight.registerLanguage('javascript', javascript);
highlight.registerLanguage('js', javascript);
highlight.registerLanguage('typescript', typescript);
highlight.registerLanguage('ts', typescript);
highlight.registerLanguage('json', json);
highlight.registerLanguage('bash', bash);
highlight.registerLanguage('sh', bash);
highlight.registerLanguage('go', go);
highlight.registerLanguage('plaintext', plaintext);
highlight.registerLanguage('text', plaintext);
highlight.registerLanguage('txt', plaintext);
highlight.registerLanguage('gitattributes', plaintext);
highlight.registerLanguage('xml', xml);
highlight.registerLanguage('python', python);
highlight.registerLanguage('py', python);
highlight.registerLanguage('ruby', ruby);
highlight.registerLanguage('rb', ruby);
highlight.registerLanguage('rust', rust);
highlight.registerLanguage('rs', rust);
highlight.registerLanguage('yaml', yaml);
highlight.registerLanguage('yml', yaml);
highlight.registerLanguage('markdown', markdown);
highlight.registerLanguage('md', markdown);
highlight.registerLanguage('cpp', cpp);
highlight.registerLanguage('c', c);
highlight.registerLanguage('csharp', csharp);
highlight.registerLanguage('cs', csharp);
highlight.registerLanguage('css', css);
highlight.registerLanguage('java', java);
highlight.registerLanguage('kotlin', kotlin);
highlight.registerLanguage('php', php);
highlight.registerLanguage('sql', sql);
highlight.registerLanguage('swift', swift);
highlight.registerLanguage('scss', scss);
highlight.registerLanguage('less', less);
highlight.registerLanguage('dockerfile', dockerfile);
highlight.registerLanguage('makefile', makefile);
highlight.registerLanguage('lua', lua);
highlight.registerLanguage('powershell', powershell);
highlight.registerLanguage('ini', ini);
highlight.registerLanguage('properties', properties);
highlight.registerLanguage('graphql', graphql);
highlight.registerLanguage('protobuf', protobuf);
highlight.registerLanguage('dart', dart);
highlight.registerLanguage('scala', scala);
highlight.registerLanguage('r', r);
highlight.registerLanguage('elixir', elixir);
highlight.registerLanguage('erlang', erlang);
highlight.registerLanguage('haskell', haskell);
highlight.registerLanguage('objectivec', objectivec);
highlight.registerLanguage('cmake', cmake);
highlight.registerLanguage('nix', nix);
highlight.registerLanguage('nginx', nginx);
highlight.registerLanguage('apache', apache);
highlight.registerLanguage('perl', perl);
highlight.registerLanguage('clojure', clojure);
highlight.registerLanguage('fsharp', fsharp);
highlight.registerLanguage('ocaml', ocaml);
highlight.registerLanguage('julia', julia);
highlight.registerLanguage('matlab', matlab);
highlight.registerLanguage('fortran', fortran);
highlight.registerLanguage('groovy', groovy);
highlight.registerLanguage('gradle', gradle);
highlight.registerLanguage('latex', latex);
highlight.registerLanguage('handlebars', handlebars);
highlight.registerLanguage('django', django);
highlight.registerLanguage('twig', twig);
highlight.registerLanguage('erb', erb);
highlight.registerLanguage('wasm', wasm);
highlight.registerLanguage('x86asm', x86asm);
highlight.registerLanguage('armasm', armasm);
highlight.registerLanguage('verilog', verilog);
highlight.registerLanguage('vhdl', vhdl);
highlight.registerLanguage('glsl', glsl);
highlight.registerLanguage('awk', awk);
highlight.registerLanguage('tcl', tcl);
highlight.registerLanguage('vim', vim);
highlight.registerLanguage('scheme', scheme);
highlight.registerLanguage('lisp', lisp);
highlight.registerLanguage('prolog', prolog);
highlight.registerLanguage('terraform', terraform);
highlight.registerLanguage('elm', elm);
highlight.registerLanguage('crystal', crystal);
highlight.registerLanguage('nim', nim);
highlight.registerLanguage('ada', ada);
highlight.registerLanguage('vbnet', vbnet);
highlight.registerLanguage('coffeescript', coffeescript);
highlight.registerLanguage('diff', diff);

const DIFF_LANGUAGE_ALIASES: Record<string, string> = {
  jsx: 'javascript',
  mjs: 'javascript',
  cjs: 'javascript',
  tsx: 'typescript',
  zsh: 'bash',
  cc: 'cpp',
  cxx: 'cpp',
  hpp: 'cpp',
  h: 'c',
};
export function highlightDiffLine(source: string, language: string): string {
  const name = DIFF_LANGUAGE_ALIASES[language] || language;
  if (!source || !highlight.getLanguage(name)) return '';
  try {
    return highlight.highlight(source, { language: name, ignoreIllegals: true }).value;
  } catch {
    return '';
  }
}
export { highlight };
