package session

import (
	"context"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"sync"
)

// handoverRandomPattern matches filenames like "2026-04-03-amber-creek-bloom.md"
// with exactly three dash-separated lowercase alpha segments after the date.
var handoverRandomPattern = regexp.MustCompile(
	`^\d{4}-\d{2}-\d{2}-([a-z]+)-([a-z]+)-([a-z]+)\.md$`,
)

// handoverWordSet is built once from handoverWords for O(1) membership checks.
var handoverWordSet = func() map[string]struct{} {
	m := make(map[string]struct{}, len(handoverWords))
	for _, w := range handoverWords {
		m[w] = struct{}{}
	}
	return m
}()

// IsRandomHandoverName returns true if the filename matches the random 3-word
// pattern generated by GetHandoverPath and all three words are from the
// handoverWords list. This prevents LLM-generated descriptive slugs (e.g.
// "fix-auth-bug") from being treated as random and renamed repeatedly.
func IsRandomHandoverName(name string) bool {
	m := handoverRandomPattern.FindStringSubmatch(name)
	if m == nil {
		return false
	}
	_, ok1 := handoverWordSet[m[1]]
	_, ok2 := handoverWordSet[m[2]]
	_, ok3 := handoverWordSet[m[3]]
	return ok1 && ok2 && ok3
}

const handoverRenameThreshold = 1000 // bytes before attempting rename

// HandoverSlugGenerator produces a short filesystem-safe slug from document content.
type HandoverSlugGenerator func(ctx context.Context, content string) (string, error)

// MaybeRenameHandover checks if the given handover file should be renamed.
// It renames when the file has a random-word name and contains >= 1000 bytes.
// After renaming, a symlink is created from the old path to the new file so
// that the system prompt path remains valid (preserving LLM cache).
//
// slugGen is called to produce the new slug; if nil or if it returns an error,
// the rename is silently skipped.
func MaybeRenameHandover(ctx context.Context, path string, slugGen HandoverSlugGenerator) error {
	base := filepath.Base(path)
	if !IsRandomHandoverName(base) {
		return nil // already renamed or not a random name
	}

	info, err := os.Stat(path)
	if err != nil || info.Size() < handoverRenameThreshold {
		return nil // file doesn't exist yet or too small
	}

	// Check if path is already a symlink (rename already happened)
	if fi, err := os.Lstat(path); err == nil && fi.Mode()&os.ModeSymlink != 0 {
		return nil
	}

	if slugGen == nil {
		return nil
	}

	content, err := os.ReadFile(path)
	if err != nil {
		return nil
	}

	slug, err := slugGen(ctx, string(content))
	if err != nil || strings.TrimSpace(slug) == "" {
		return nil // silently skip on error
	}

	// Sanitize slug: lowercase, replace spaces/special chars with dashes, limit length
	slug = sanitizeSlug(slug)
	if slug == "" {
		return nil
	}

	// Build new name: preserve the date prefix, replace the random words
	// "2026-04-03-amber-creek-bloom.md" → "2026-04-03-fix-auth-migration.md"
	datePrefix := base[:10] // "2026-04-03"
	newName := datePrefix + "-" + slug + ".md"
	dir := filepath.Dir(path)
	newPath := filepath.Join(dir, newName)

	// Don't overwrite an existing file
	if _, err := os.Stat(newPath); err == nil {
		return nil
	}

	// Rename the file
	if err := os.Rename(path, newPath); err != nil {
		return fmt.Errorf("handover rename: %w", err)
	}

	// Create symlink: old random name → new descriptive name (relative)
	if err := os.Symlink(newName, path); err != nil {
		// Rename succeeded but symlink failed — try to rename back
		_ = os.Rename(newPath, path)
		return fmt.Errorf("handover symlink: %w", err)
	}

	return nil
}

var handoverPrettifyMu sync.Mutex

// PrettifyHandoverName renames a random-named handover file to a short
// descriptive name derived from the session's first user message, so the file
// has a nice name from the start. The original random path — baked into the
// session's system prompt — keeps working via a symlink. When the agent has
// not written the file yet, an empty descriptive target is atomically reserved
// before the symlink is created so concurrent sessions cannot share a target.
//
// slugGen receives the description and should return roughly two words; the
// result is sanitized and capped at two dash-separated words. Errors from
// slugGen are silently skipped — the file simply keeps its random name.
func PrettifyHandoverName(ctx context.Context, path, description string, slugGen HandoverSlugGenerator) error {
	base := filepath.Base(path)
	if !IsRandomHandoverName(base) {
		return nil // already renamed or not a random name
	}
	if fi, err := os.Lstat(path); err == nil && fi.Mode()&os.ModeSymlink != 0 {
		return nil // already prettified
	}
	if slugGen == nil || strings.TrimSpace(description) == "" {
		return nil
	}

	slug, err := slugGen(ctx, description)
	if err != nil || strings.TrimSpace(slug) == "" {
		return nil // silently skip on error
	}
	slug = limitSlugWords(sanitizeSlug(slug), 2)
	if slug == "" {
		return nil
	}

	datePrefix := base[:10] // "2026-04-03"
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("handover prettify mkdir: %w", err)
	}

	// Candidate reservation and replacement of the source path must be one
	// in-process transaction. Atomic O_EXCL creation (unwritten source) or hard
	// linking (written source) also prevents another process from overwriting a
	// destination between an existence check and rename.
	handoverPrettifyMu.Lock()
	defer handoverPrettifyMu.Unlock()

	if fi, err := os.Lstat(path); err == nil && fi.Mode()&os.ModeSymlink != 0 {
		return nil
	}

	words := handoverRandomPattern.FindStringSubmatch(base)
	if words == nil {
		return nil
	}
	candidates := []string{
		datePrefix + "-" + slug + ".md",
		datePrefix + "-" + slug + "-" + words[1] + ".md",
		datePrefix + "-" + slug + "-" + words[1] + "-" + words[2] + ".md",
		datePrefix + "-" + slug + "-" + words[1] + "-" + words[2] + "-" + words[3] + ".md",
	}

	sourceInfo, sourceErr := os.Lstat(path)
	sourceExists := sourceErr == nil
	if sourceErr != nil && !errors.Is(sourceErr, os.ErrNotExist) {
		return fmt.Errorf("handover prettify source: %w", sourceErr)
	}
	if sourceExists && !sourceInfo.Mode().IsRegular() {
		return nil
	}

	var newName, newPath string
	for _, candidate := range candidates {
		candidatePath := filepath.Join(dir, candidate)
		err := reserveHandoverDestination(path, candidatePath, sourceExists)
		if errors.Is(err, os.ErrExist) {
			continue
		}
		if err != nil {
			return fmt.Errorf("handover prettify reserve: %w", err)
		}
		newName, newPath = candidate, candidatePath
		break
	}
	if newPath == "" {
		return nil
	}

	if sourceExists {
		if err := os.Remove(path); err != nil {
			_ = os.Remove(newPath)
			return fmt.Errorf("handover prettify remove source: %w", err)
		}
	}
	if err := os.Symlink(newName, path); err != nil {
		if sourceExists {
			// Keep the reserved destination if another process occupied the
			// source path before it could be restored; it is then the only link
			// that still preserves this session's plan.
			if restoreErr := os.Link(newPath, path); restoreErr == nil {
				_ = os.Remove(newPath)
			}
		} else {
			_ = os.Remove(newPath)
		}
		return fmt.Errorf("handover prettify symlink: %w", err)
	}
	return nil
}

// reserveHandoverDestination claims dst without ever replacing it. A hard link
// carries an existing source's inode and content; O_EXCL reserves an empty file
// before an unwritten source is redirected through its symlink.
func reserveHandoverDestination(src, dst string, sourceExists bool) error {
	if sourceExists {
		return os.Link(src, dst)
	}
	f, err := os.OpenFile(dst, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o644)
	if err != nil {
		return err
	}
	if err := f.Close(); err != nil {
		_ = os.Remove(dst)
		return err
	}
	return nil
}

// limitSlugWords truncates a dash-separated slug to at most n words.
func limitSlugWords(slug string, n int) string {
	parts := strings.Split(slug, "-")
	if len(parts) > n {
		parts = parts[:n]
	}
	return strings.Join(parts, "-")
}

func sanitizeSlug(s string) string {
	s = strings.ToLower(strings.TrimSpace(s))
	// Replace any non-alphanumeric chars with dashes
	var b strings.Builder
	prev := false
	for _, r := range s {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') {
			b.WriteRune(r)
			prev = false
		} else if !prev {
			b.WriteByte('-')
			prev = true
		}
	}
	result := strings.Trim(b.String(), "-")
	// Limit to 50 chars
	if len(result) > 50 {
		result = result[:50]
		// Don't end mid-word
		if i := strings.LastIndex(result, "-"); i > 20 {
			result = result[:i]
		}
	}
	return result
}
