package serveui

import (
	"bytes"
	"crypto/sha256"
	"embed"
	"encoding/hex"
	"fmt"
	htmlpkg "html"
	"io/fs"
	"sort"
	"strings"
	"sync"
)

// Frontend assets are generated by `make frontend` before compiling the Go
// binary. The all: prefix intentionally embeds deterministic chunks.
//
//go:embed static/index.html static/manifest.webmanifest static/icon-512.png static/sw.js
//go:embed all:static/dist
var staticFiles embed.FS

var (
	assetVersionOnce sync.Once
	assetVersion     string

	renderManifestOnce sync.Once
	renderManifest     []byte

	renderServiceWorkerOnce sync.Once
	renderServiceWorker     []byte
)

// AssetVersion returns a stable hash of every embedded UI asset.
func AssetVersion() string {
	assetVersionOnce.Do(func() {
		entries := make([]string, 0, 16)
		_ = fs.WalkDir(staticFiles, "static", func(path string, d fs.DirEntry, err error) error {
			if err != nil || d.IsDir() {
				return err
			}
			entries = append(entries, path)
			return nil
		})
		sort.Strings(entries)
		h := sha256.New()
		for _, path := range entries {
			data, err := fs.ReadFile(staticFiles, path)
			if err != nil {
				continue
			}
			_, _ = h.Write([]byte(path))
			_, _ = h.Write([]byte{0})
			_, _ = h.Write(data)
			_, _ = h.Write([]byte{0})
		}
		assetVersion = hex.EncodeToString(h.Sum(nil))[:12]
	})
	return assetVersion
}

func versioned(path string) string { return path + "?v=" + AssetVersion() }

// IndexHTML returns the embedded UI page.
func IndexHTML() []byte {
	data, err := StaticAsset("index.html")
	if err != nil {
		return nil
	}
	return data
}

// RenderOptions controls optional UI features included in rendered UI assets.
type RenderOptions struct {
	WebRTC bool
}

// RenderIndexHTML returns the Preact entry page with versioned cacheable assets,
// a canonical network-first module entry, caller-supplied head markup, and the
// exact relative base-path contract.
func RenderIndexHTML(basePath, headSnippet string, _ RenderOptions) []byte {
	html := IndexHTML()
	if len(html) == 0 {
		return nil
	}
	for _, replacement := range []struct{ old, new string }{
		{`href="icon-512.png"`, `href="` + versioned("icon-512.png") + `"`},
		{`href="manifest.webmanifest"`, `href="` + versioned("manifest.webmanifest") + `"`},
		{`href="dist/app.css"`, `href="` + versioned("dist/app.css") + `"`},
	} {
		html = bytes.ReplaceAll(html, []byte(replacement.old), []byte(replacement.new))
	}

	baseTag := `<base href="` + htmlpkg.EscapeString(basePath) + `/">`
	html = bytes.Replace(html, []byte(`<meta charset="utf-8">`), []byte(`<meta charset="utf-8">`+"\n  "+baseTag), 1)
	if headSnippet != "" {
		html = bytes.Replace(html, []byte("</head>"), []byte(headSnippet+"</head>"), 1)
	}
	return html
}

// RenderManifest returns the manifest with versioned icon URLs. The returned
// slice is cached and must be treated as read-only.
func RenderManifest() []byte {
	renderManifestOnce.Do(func() {
		data, err := StaticAsset("manifest.webmanifest")
		if err == nil {
			renderManifest = bytes.ReplaceAll(data, []byte(`"./icon-512.png"`), []byte(`"./`+versioned("icon-512.png")+`"`))
		}
	})
	return renderManifest
}

// RenderServiceWorker returns the service worker with a versioned cache key and
// generated shell asset URLs. The canonical app entry and stable-named Vite
// chunks deliberately remain unversioned and network-first so every import uses
// one module identity and deployments cannot execute an old dependency graph.
func RenderServiceWorker(_ RenderOptions) []byte {
	renderServiceWorkerOnce.Do(func() {
		data, err := StaticAsset("sw.js")
		if err != nil {
			return
		}
		for _, replacement := range []struct{ old, new string }{
			{"term-llm-shell-v6", "term-llm-shell-" + AssetVersion()},
			{"'./manifest.webmanifest'", "'./" + versioned("manifest.webmanifest") + "'"},
			{"'./icon-512.png'", "'./" + versioned("icon-512.png") + "'"},
			{"'./dist/app.css'", "'./" + versioned("dist/app.css") + "'"},
		} {
			data = bytes.ReplaceAll(data, []byte(replacement.old), []byte(replacement.new))
		}
		renderServiceWorker = data
	})
	return renderServiceWorker
}

// StaticAsset returns a copy of an embedded serve-ui asset.
func StaticAsset(name string) ([]byte, error) {
	cleanName := strings.TrimSpace(strings.TrimPrefix(name, "/"))
	if cleanName == "" || strings.Contains(cleanName, "..") {
		return nil, fmt.Errorf("invalid asset name %q", name)
	}
	data, err := fs.ReadFile(staticFiles, "static/"+cleanName)
	if err != nil {
		return nil, err
	}
	return bytes.Clone(data), nil
}
