package serveui

import (
	"bytes"
	"crypto/sha256"
	"embed"
	"encoding/hex"
	"encoding/json"
	"fmt"
	htmlpkg "html"
	"io/fs"
	"sort"
	"strings"
	"sync"
)

// Frontend assets are generated by `make frontend` before compiling the Go
// binary. The all: prefix intentionally embeds hashed chunks and the manifest.
//
//go:embed static/index.html static/manifest.webmanifest static/icon-512.png static/sw.js
//go:embed all:static/dist
var staticFiles embed.FS

var (
	assetVersionOnce sync.Once
	assetVersion     string

	hubAssetVersionOnce sync.Once
	hubAssetVersion     string

	renderManifestOnce sync.Once
	renderManifest     []byte

	renderServiceWorkerOnce sync.Once
	renderServiceWorker     []byte
)

// AssetVersion returns a stable hash of the chat UI assets. The standalone Hub
// entry has an independent version so changes to either application do not
// rotate the other application's cache identity.
func AssetVersion() string {
	assetVersionOnce.Do(func() {
		assetVersion = embeddedAssetVersion(func(path string) bool {
			return path != "static/dist/hub.js" && path != "static/dist/hub.css"
		})
	})
	return assetVersion
}

// HubAssetVersion returns a stable hash over exactly the standalone Hub entry
// module and stylesheet.
func HubAssetVersion() string {
	hubAssetVersionOnce.Do(func() {
		hubAssetVersion = embeddedAssetVersion(func(path string) bool {
			return path == "static/dist/hub.js" || path == "static/dist/hub.css"
		})
	})
	return hubAssetVersion
}

func embeddedAssetVersion(include func(string) bool) string {
	entries := make([]string, 0, 16)
	_ = fs.WalkDir(staticFiles, "static", func(path string, d fs.DirEntry, err error) error {
		if err != nil || d.IsDir() {
			return err
		}
		if include(path) {
			entries = append(entries, path)
		}
		return nil
	})
	sort.Strings(entries)
	h := sha256.New()
	for _, path := range entries {
		data, err := fs.ReadFile(staticFiles, path)
		if err != nil {
			continue
		}
		_, _ = h.Write([]byte(path))
		_, _ = h.Write([]byte{0})
		_, _ = h.Write(data)
		_, _ = h.Write([]byte{0})
	}
	return hex.EncodeToString(h.Sum(nil))[:12]
}

func versioned(path string) string { return path + "?v=" + AssetVersion() }

// IndexHTML returns the embedded UI page.
func IndexHTML() []byte {
	data, err := StaticAsset("index.html")
	if err != nil {
		return nil
	}
	return data
}

// RenderOptions controls optional UI features included in rendered UI assets.
type RenderOptions struct {
	WebRTC bool
}

// RenderIndexHTML returns the Preact entry page with versioned cacheable assets,
// a content-addressed module graph, caller-supplied head markup, and the
// exact relative base-path contract.
func RenderIndexHTML(basePath, headSnippet string, _ RenderOptions) []byte {
	html := IndexHTML()
	if len(html) == 0 {
		return nil
	}
	manifest := ChatAssetManifest()
	for _, replacement := range []struct{ old, new string }{
		{`href="icon-512.png"`, `href="` + versioned("icon-512.png") + `"`},
		{`href="manifest.webmanifest"`, `href="` + versioned("manifest.webmanifest") + `"`},
		{`href="dist/app.css"`, `href="` + manifest.EntryCSS[0] + `"`},
		{`src="dist/app.js"`, `src="` + manifest.EntryJS + `"`},
	} {
		html = bytes.ReplaceAll(html, []byte(replacement.old), []byte(replacement.new))
	}

	baseTag := `<base href="` + htmlpkg.EscapeString(basePath) + `/">`
	html = bytes.Replace(html, []byte(`<meta charset="utf-8">`), []byte(`<meta charset="utf-8">`+"\n  "+baseTag), 1)
	if headSnippet != "" {
		html = bytes.Replace(html, []byte("</head>"), []byte(headSnippet+"</head>"), 1)
	}
	return html
}

// RenderManifest returns the manifest with versioned icon URLs. The returned
// slice is cached and must be treated as read-only.
func RenderManifest() []byte {
	renderManifestOnce.Do(func() {
		data, err := StaticAsset("manifest.webmanifest")
		if err == nil {
			renderManifest = bytes.ReplaceAll(data, []byte(`"./icon-512.png"`), []byte(`"./`+versioned("icon-512.png")+`"`))
		}
	})
	return renderManifest
}

// RenderServiceWorker injects the version-scoped shell and complete hashed graph.
// Content-addressed assets are cache-first across updates; activation retains the
// current and previous deployment's cached files for open clients. HTTP immutable
// caching also works without a service worker (including WKWebView). No URL ever
// serves a different graph member: removed old chunks return 404, not newer bytes.
func RenderServiceWorker(_ RenderOptions) []byte {
	renderServiceWorkerOnce.Do(func() {
		data, err := StaticAsset("sw.js")
		if err != nil {
			return
		}
		for _, replacement := range []struct{ old, new string }{
			{"term-llm-shell-v7", "term-llm-shell-" + AssetVersion()},
			{"'./manifest.webmanifest'", "'./" + versioned("manifest.webmanifest") + "'"},
			{"'./icon-512.png'", "'./" + versioned("icon-512.png") + "'"},
		} {
			data = bytes.ReplaceAll(data, []byte(replacement.old), []byte(replacement.new))
		}

		paths := ChatAssetManifest().Files
		urls := make([]string, len(paths))
		for i, path := range paths {
			urls[i] = "./" + path
		}
		assets, _ := json.Marshal(urls)
		data = bytes.ReplaceAll(data, []byte("const HASHED_ASSETS = [];"), []byte("const HASHED_ASSETS = "+string(assets)+";"))
		renderServiceWorker = data
	})
	return renderServiceWorker
}

// StaticAsset returns a copy of an embedded serve-ui asset.
func StaticAsset(name string) ([]byte, error) {
	cleanName := strings.TrimSpace(strings.TrimPrefix(name, "/"))
	if cleanName == "" || strings.Contains(cleanName, "..") {
		return nil, fmt.Errorf("invalid asset name %q", name)
	}
	data, err := fs.ReadFile(staticFiles, "static/"+cleanName)
	if err != nil {
		return nil, err
	}
	return bytes.Clone(data), nil
}

// SourceAssetPaths lists static, credential-free chat source assets for agent inspection.
func SourceAssetPaths() []string {
	paths := []string{"index.html", "sw.js"}
	_ = fs.WalkDir(staticFiles, "static/dist", func(p string, d fs.DirEntry, err error) error {
		if err == nil && !d.IsDir() && !strings.HasSuffix(p, "/hub.js") && !strings.HasSuffix(p, "/hub.css") && (strings.HasSuffix(p, ".css") || strings.HasSuffix(p, ".js")) {
			paths = append(paths, strings.TrimPrefix(p, "static/"))
		}
		return err
	})
	sort.Strings(paths)
	return paths
}
