'use strict';
const assert = require('assert');
const fields={displayName:{value:'Replacement key'},setupCode:{value:'new-bootstrap-code'}};
global.document = {body:{dataset:{mode:'',basePath:'/hub'}},getElementById:(id)=>fields[id]||null};
global.window = {};global.sessionStorage={getItem:()=>null,setItem:()=>{},removeItem:()=>{}};
const auth = require('./hub_auth.js');
const original = Uint8Array.from([0,1,2,253,254,255]);
const encoded = auth.bytesToB64url(original);
assert.strictEqual(encoded, 'AAEC_f7_');
assert.deepStrictEqual(Array.from(auth.b64urlToBytes(encoded)), Array.from(original));
assert.strictEqual(auth.endpoint('/api/auth/session'), '/hub/api/auth/session');
const creation=auth.decodeCreation({publicKey:{challenge:'AAEC',user:{id:'_w'},excludeCredentials:[{id:'AQ'}]}});
assert.deepStrictEqual(Array.from(creation.publicKey.challenge),[0,1,2]);
assert.deepStrictEqual(Array.from(creation.publicKey.user.id),[255]);
const request=auth.decodeRequest({publicKey:{challenge:'AQ',allowCredentials:[{id:'Ag'}]}});
assert.deepStrictEqual(Array.from(request.publicKey.allowCredentials[0].id),[2]);
assert.strictEqual(auth.passkeysAvailable(),false);
assert.match(auth.authErrorMessage({name:'NotAllowedError'}),/cancelled or timed out/);
assert.strictEqual(auth.authErrorMessage(new Error('unsupported browser')),'unsupported browser');
const serialized=auth.serialize({id:'cred',rawId:original.buffer,type:'public-key',response:{clientDataJSON:Uint8Array.from([1]).buffer,authenticatorData:Uint8Array.from([2]).buffer,signature:Uint8Array.from([3]).buffer,userHandle:null},getClientExtensionResults:()=>({})});
assert.strictEqual(serialized.rawId,encoded);assert.strictEqual(serialized.response.signature,'Aw');
(async()=>{
  const calls=[];
  Object.defineProperty(global.navigator,'credentials',{configurable:true,value:{create:async()=>({id:'new',rawId:Uint8Array.from([9]).buffer,type:'public-key',response:{clientDataJSON:Uint8Array.from([1]).buffer,attestationObject:Uint8Array.from([2]).buffer,getTransports:()=>['internal']},getClientExtensionResults:()=>({})})}});
  global.fetch=async(url)=>{calls.push(url);if(calls.length===1)return new Response('{"error":{"message":"expired grant"}}',{status:401,headers:{'Content-Type':'application/json'}});if(calls.length===2)return new Response('{"ok":true}',{status:200,headers:{'Content-Type':'application/json'}});if(calls.length===3)return new Response(JSON.stringify({publicKey:{challenge:'AQ',user:{id:'Ag'},excludeCredentials:[]}}),{status:200,headers:{'Content-Type':'application/json'}});return new Response('{"ok":true}',{status:201,headers:{'Content-Type':'application/json'}});};
  auth.setGrantVerified(true);
  await auth.registerWithGrant('/api/auth/bootstrap');
  assert.deepStrictEqual(calls,['/hub/api/auth/bootstrap/register/begin','/hub/api/auth/bootstrap/verify','/hub/api/auth/bootstrap/register/begin','/hub/api/auth/bootstrap/register/finish']);
  console.log('hub_auth.js tests passed');
})().catch(error=>{console.error(error);process.exitCode=1;});
