package complexity

import (
	"os"
	"path/filepath"
	"testing"
)

func TestAnalyzeCountingRulesAndInitializers(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	writeTestFile(t, root, "go.mod", "module example.com/root\n\ngo 1.25\n")
	writeTestFile(t, root, "p/source.go", `package p
var initFn = func(x bool) { if x || !x {} }
func plain() {}
func branches(a, b bool, xs []int, ch chan int) {
 if a && b {}
 for {}
 for range xs {}
 switch { case a:; default: }
 select { case <-ch:; default: }
 _ = func() { if a {} }
}
`)
	report, err := Analyze(root, Options{})
	if err != nil {
		t.Fatal(err)
	}
	got := map[string]Function{}
	for _, fn := range report.Functions {
		got[fn.Name] = fn
	}
	if got["plain"].Complexity != 1 {
		t.Fatalf("plain complexity = %d", got["plain"].Complexity)
	}
	if got["initFn"].Complexity != 3 {
		t.Fatalf("initializer complexity = %d", got["initFn"].Complexity)
	}
	// base + if + && + two fors + switch case + select case + literal if
	if got["branches"].Complexity != 8 {
		t.Fatalf("branches complexity = %d", got["branches"].Complexity)
	}
}

func TestAnalyzeScopeGeneratedTestsNestedAndStableOrder(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	writeTestFile(t, root, "go.mod", "module root\n\ngo 1.25\n")
	writeTestFile(t, root, "z.go", "package root\nfunc Z() {}\n")
	writeTestFile(t, root, "a_test.go", "package root\nfunc TestA() {}\n")
	writeTestFile(t, root, "generated.go", "// Code generated by test. DO NOT EDIT.\npackage root\nfunc Generated() {}\n")
	writeTestFile(t, root, ".cache/ignored.go", "package cache\nfunc Cached() { if true {} }\n")
	writeTestFile(t, root, "testdata/ignored.go", "package fixture\nfunc Fixture() { if true {} }\n")
	writeTestFile(t, root, "internal/serveui/static/dist/ignored.go", "package dist\nfunc Bundled() {}\n")
	writeTestFile(t, root, "internal/serveui/static/dist2/kept.go", "package dist2\nfunc Kept() {}\n")
	writeTestFile(t, root, "nested/go.mod", "module nested\n\ngo 1.25\n")
	writeTestFile(t, root, "nested/n.go", "package nested\nfunc N() {}\n")

	prod, err := Analyze(root, Options{})
	if err != nil {
		t.Fatal(err)
	}
	if len(prod.Functions) != 3 {
		t.Fatalf("production functions = %#v", prod.Functions)
	}
	if len(prod.Files) != 3 {
		t.Fatalf("production files = %#v", prod.Files)
	}
	if prod.Functions[0].Path != "internal/serveui/static/dist2/kept.go" || prod.Functions[1].Path != "nested/n.go" || prod.Functions[1].Module != "nested" || prod.Functions[2].Path != "z.go" {
		t.Fatalf("unstable/wrong traversal: %#v", prod.Functions)
	}
	all, err := Analyze(root, Options{IncludeTests: true})
	if err != nil {
		t.Fatal(err)
	}
	if len(all.Functions) != 4 || !all.Functions[0].Test {
		t.Fatalf("test split = %#v", all.Functions)
	}
}

func TestAnalyzeMalformedSourceFails(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	writeTestFile(t, root, "go.mod", "module root\n\ngo 1.25\n")
	writeTestFile(t, root, "bad.go", "package root\nfunc broken(\n")
	if _, err := Analyze(root, Options{}); err == nil {
		t.Fatal("expected parse failure")
	}
}

func writeTestFile(t *testing.T, root, name, content string) {
	t.Helper()
	path := filepath.Join(root, name)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}
